In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import roc_auc_score

In [3]:
telecom=pd.read_csv("D:/onkar_cdac/C-DAC/PML/PML/Files_by_sir/5. PML/1. Day wise Study Material/Cases/Telecom/Telecom.csv")

In [4]:
telecom

Gender TT_gt_100 Response
0        F         Y        N
1        M         N        N
2        M         N        N
3        F         Y        Y
4        F         N        N
..     ...       ...      ...
145      F         Y        Y
146      M         N        Y
147      M         N        N
148      M         N        N
149      F         N        N

[150 rows x 3 columns]

In [9]:
dum_tel = pd.get_dummies(telecom,drop_first=True)

In [10]:
dum_tel

Gender_M  TT_gt_100_Y  Response_Y
0           0            1           0
1           1            0           0
2           1            0           0
3           0            1           1
4           0            0           0
..        ...          ...         ...
145         0            1           1
146         1            0           1
147         1            0           0
148         1            0           0
149         0            0           0

[150 rows x 3 columns]

In [11]:
X=dum_tel.drop('Response_Y',axis=1)
y=dum_tel['Response_Y']

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2023,
                                              test_size=0.30,stratify=y)

In [13]:
nb=BernoulliNB()
nb.fit(X_train,y_train)

BernoulliNB()

In [14]:
pred=nb.predict(X_test)

In [15]:
pred

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1], dtype=uint8)

In [16]:
y_pred_prob = nb.predict_proba(X_test)[:,1]

In [17]:
y_pred_prob

array([0.939927  , 0.47178064, 0.46811645, 0.04783655, 0.04783655,
       0.939927  , 0.04783655, 0.47178064, 0.939927  , 0.04783655,
       0.939927  , 0.47178064, 0.04783655, 0.47178064, 0.939927  ,
       0.939927  , 0.939927  , 0.939927  , 0.04783655, 0.47178064,
       0.939927  , 0.04783655, 0.939927  , 0.939927  , 0.04783655,
       0.939927  , 0.939927  , 0.939927  , 0.04783655, 0.04783655,
       0.47178064, 0.939927  , 0.04783655, 0.939927  , 0.939927  ,
       0.47178064, 0.47178064, 0.04783655, 0.04783655, 0.04783655,
       0.47178064, 0.04783655, 0.939927  , 0.46811645, 0.939927  ])

In [18]:
print(roc_auc_score(y_test, y_pred_prob))

0.8972332015810276


In [19]:
tst_tel = pd.read_csv("D:/onkar_cdac/C-DAC/PML/PML/Files_by_sir/5. PML/1. Day wise Study Material/Cases/Telecom/testTelecom.csv")
dum_tst = pd.get_dummies(tst_tel, drop_first=True)

In [20]:
dum_tst

Gender_M  TT_gt_100_Y
0          0            1
1          1            1
2          0            0
3          1            0
4          0            0
5          0            1
6          1            0
7          1            1
8          0            0
9          0            1
10         0            0
11         1            0
12         1            1
13         0            1
14         0            0
15         0            0
16         0            1
17         1            1
18         1            0
19         1            0

In [21]:
predictions = nb.predict(dum_tst)

In [22]:
predictions

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
      dtype=uint8)

In [23]:
np.sum(predictions)

5

In [24]:
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=2022)
nb = BernoulliNB()
results = cross_val_score(nb, X, y, scoring='roc_auc', cv=kfold)
print(results)
print(results.mean())

[0.98888889 0.90666667 0.81026786 0.85267857 0.859375  ]
0.8835753968253968


In [25]:
# Building the model on whole data
nb.fit(X,y)
predict_probs = nb.predict_proba(dum_tst)
predictions = nb.predict(dum_tst)
np.sum(predictions)

5

In [26]:
predictions

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
      dtype=uint8)

In [27]:
############# Cancer Data #######################

In [29]:
cancer = pd.read_csv("D:/onkar_cdac/C-DAC/PML/PML/Files_by_sir/5. PML/1. Day wise Study Material/Cases/Cancer/Cancer.csv", index_col=0)

In [30]:
cancer

age menopause tumor-size inv-nodes node-caps  deg-malig breast  \
subjid                                                                     
1       40-49   premeno      15-19       0-2       yes          3  right   
2       50-59      ge40      15-19       0-2        no          1  right   
3       50-59      ge40      35-39       0-2        no          2   left   
4       40-49   premeno      35-39       0-2       yes          3  right   
5       40-49   premeno      30-34       3-5       yes          2   left   
...       ...       ...        ...       ...       ...        ...    ...   
282     50-59      ge40      30-34       6-8       yes          2   left   
283     50-59   premeno      25-29       3-5       yes          2   left   
284     30-39   premeno      30-34       6-8       yes          2  right   
285     50-59   premeno      15-19       0-2        no          2  right   
286     50-59      ge40      40-44       0-2        no          3   left   

       breast-quad irradiat                 Class  
subjid                                             
1          left_up       no     recurrence-events  
2          central       no  no-recurrence-events  
3         left_low       no     recurrence-events  
4         left_low      yes  no-recurrence-events  
5         right_up       no     recurrence-events  
...            ...      ...                   ...  
282       left_low       no  no-recurrence-events  
283       left_low      yes  no-recurrence-events  
284       right_up       no  no-recurrence-events  
285       left_low       no  no-recurrence-events  
286       right_up       no  no-recurrence-events  

[286 rows x 10 columns]

In [32]:
dum_cancer = pd.get_dummies(cancer, drop_first=True)

In [33]:
dum_cancer

deg-malig  age_30-39  age_40-49  age_50-59  age_60-69  age_70-79  \
subjid                                                                     
1               3          0          1          0          0          0   
2               1          0          0          1          0          0   
3               2          0          0          1          0          0   
4               3          0          1          0          0          0   
5               2          0          1          0          0          0   
...           ...        ...        ...        ...        ...        ...   
282             2          0          0          1          0          0   
283             2          0          0          1          0          0   
284             2          1          0          0          0          0   
285             2          0          0          1          0          0   
286             3          0          0          1          0          0   

        menopause_lt40  menopause_premeno  tumor-size_10-14  tumor-size_15-19  \
subjid                                                                          
1                    0                  1                 0                 1   
2                    0                  0                 0                 1   
3                    0                  0                 0                 0   
4                    0                  1                 0                 0   
5                    0                  1                 0                 0   
...                ...                ...               ...               ...   
282                  0                  0                 0                 0   
283                  0                  1                 0                 0   
284                  0                  1                 0                 0   
285                  0                  1                 0                 1   
286                  0                  0                 0                 0   

        ...  inv-nodes_6-8  inv-nodes_9-11  node-caps_yes  breast_right  \
subjid  ...                                                               
1       ...              0               0              1             1   
2       ...              0               0              0             1   
3       ...              0               0              0             0   
4       ...              0               0              1             1   
5       ...              0               0              1             0   
...     ...            ...             ...            ...           ...   
282     ...              1               0              1             0   
283     ...              0               0              1             0   
284     ...              1               0              1             1   
285     ...              0               0              0             1   
286     ...              0               0              0             0   

        breast-quad_left_low  breast-quad_left_up  breast-quad_right_low  \
subjid                                                                     
1                          0                    1                      0   
2                          0                    0                      0   
3                          1                    0                      0   
4                          1                    0                      0   
5                          0                    0                      0   
...                      ...                  ...                    ...   
282                        1                    0                      0   
283                        1                    0                      0   
284                        0                    0                      0   
285                        1                    0                      0   
286                        0                    0                      0   



In [35]:
X=dum_cancer.drop('Class_recurrence-events',axis=1)
y=dum_cancer['Class_recurrence-events']

In [37]:
####### K-Folds CV
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=2023)

In [38]:
nb=BernoulliNB()

In [39]:
results=cross_val_score(nb,X,y,scoring='roc_auc',cv=kfold)
print(results)

[0.67790531 0.73529412 0.62205882 0.61764706 0.62352941]


In [40]:
print(results.mean())

0.655286944045911
